[package]
name = "mapgame"
version = "0.1.0"
authors = ["Alex Hicks <alex@alexhicks.net>"]
edition = "2024"
license = "MIT"
publish = false

[dependencies]
geojson = "0.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sfml = "0.24"
