[package]
name = "mapgame"
version = "0.1.0"
authors = ["Alex Hicks <alex@alexhicks.net>"]
edition = "2021"
license = "MIT"
publish = false

[dependencies]
futures = "0.3.28"
geojson = "0.24.1"
reqwest = "0.11.18"
sfml = "0.20.0"
tokio = { version = "1.28.1", features = ["full"] }
