[package]
name = "mapgame"
version = "0.1.0"
authors = ["Alex Hicks <alex@alexhicks.net>"]
edition = "2021"
license = "MIT"
publish = false

[dependencies]
geojson = "0.24.2"
serde = "1.0.219"
serde_json = "1.0.140"
sfml = "0.24.0"
