[package]
name = "mapgame"
version = "0.1.0"
authors = ["Alex Hicks <alex@alexhicks.net>"]
edition = "2021"
license = "MIT"
publish = false

[dependencies]
geojson = "0.24.1"
serde = "1.0.164"
serde_json = "1.0.97"
sfml = "0.21.0"
