name: Build clients
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
      - name: setup sfml
        run: |
          wget https://www.sfml-dev.org/files/SFML-2.5.1-windows-vc15-64-bit.zip
      - uses: actions-rs/cargo@v1
        name: cargo fmt
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        name: cargo build
        with:
          command: build
          args: --release --target x86_64-pc-windows-msvc
      - uses: softprops/action-gh-release@v1
        name: create release
        with:
          files: mapwar-x64.exe
