name: Build clients
permissions:
  contents: write
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install sfml
        run: sudo apt-get update && sudo apt-get install -y libsfml-dev
      - name: cargo fmt
        run: cargo fmt --all -- --check
      - name: cargo build
        run: |
          set -e
          cargo build --release
          mv ./target/release/mapwar ./mapwar-linux-x64
        env:
          CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
      - uses: softprops/action-gh-release@v1
        name: create release
        with:
          files: mapwar-linux-x64
