name: Publish Linux release
permissions:
  contents: write
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install SFML
        run: sudo apt-get update && sudo apt-get install -y libsfml-dev
      - name: Lint
        run: cargo fmt --all -- --check
      - name: Build
        run: |
          set -e
          cargo build --release
          mv ./target/release/mapwar ./mapwar-linux-x64
        env:
          CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: mapwar-linux-x64
